name: ML Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-train:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests with pytest
      run: |
        pytest test_model.py --cov=. --cov-report=xml
                
    - name: Train model
      run: |
        mkdir -p artifacts/models
        python train.py --epochs 1 --batch-size 128 --visualize True
        
    - name: Upload trained models
      uses: actions/upload-artifact@v3
      with:
        name: trained-models
        path: artifacts/models/
        retention-days: 15
        
    - name: Upload training metrics
      uses: actions/upload-artifact@v3
      with:
        name: training-metrics
        path: |
          artifacts/training_metrics.txt
          visualizations/
        retention-days: 15
        
    - name: Create model info
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        echo "Training completed at $(date)" >> artifacts/model_info.txt
        echo "Latest model accuracy can be found in training_metrics.txt" >> artifacts/model_info.txt
        
    - name: Upload model info
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v3
      with:
        name: model-info
        path: artifacts/model_info.txt
        retention-days: 15